apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smtp
resources:
- ../common/secretproviderclasses
- ../common/smtp
patches:
- path: secretproviderclass.yaml
- path: service.yaml
- path: configmap.yaml
- path: deployment.yaml
- target:
    kind: SecretProviderClass
    name: sc-kv-test
  patch: |-
    - op: replace
      path: /metadata/name
      value: smtp
configMapGenerator:
  - name: test-ca 
    files:
      - test-ca.pem=your-ca.crt
generatorOptions:
  disableNameSuffixHash: true
