apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-test
spec:
  parameters:
    objects: |
      array:
        - |
          objectName: smtp-cisco-ces-user
          objectType: secret
        - |
          objectName: smtp-cisco-ces-password
          objectType: secret
        - |
          objectName: smtp-tls
          objectType: secret
        - |
          objectName: smtp-ldap-password
          objectType: secret
        - |
          objectName: smtp-ldap-user
          objectType: secret
  secretObjects:
  - secretName: smtp
    type: Opaque
    data:
    - objectName: smtp-cisco-ces-user
      key: RELAY_USER
    - objectName: smtp-cisco-ces-password
      key: RELAY_PASSWORD
    - objectName: smtp-ldap-password
      key: LDAP_BIND_PW
    - objectName: smtp-ldap-user
      key: LDAP_BIND_DN
  - secretName: smtp-tls
    type: kubernetes.io/tls
    data: 
    - objectName: smtp-tls
      key: tls.key
    - objectName: smtp-tls
      key: tls.crt
