apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp
data:
  DEFAULT_RELAY_HOST: '[smtp-relay.test.internal]:587'
  RELAY_HOST: smtp-relay.test.internal
  RELAY_PORT: '587'
  POSTSCREEN_ACTION: drop
  POSTFIX_INET_PROTOCOLS: ipv4
  ENABLE_UPDATE_CHECK: '0'
  ENABLE_AMAVIS: '0'
  SSL_TYPE: manual
  SSL_CERT_PATH: /mnt/secrets-store/smtp-tls.crt
  SSL_KEY_PATH: /mnt/secrets-store/smtp-tls.key
  ONE_DIR: '0'
  SPOOF_PROTECTION: '1'
  ENABLE_OPENDMARC: '0'
  POSTFIX_MESSAGE_SIZE_LIMIT: '51200000'
  # >>> Postfix LDAP Integration
  ACCOUNT_PROVISIONER: LDAP
  LDAP_QUERY_FILTER_USER: (&(objectClass=user)(cn=%u))
  LDAP_QUERY_FILTER_ALIAS: (&(objectClass=user)(cn=%u))
  LDAP_QUERY_FILTER_GROUP: (&(objectClass=group)(cn=%u))
  LDAP_QUERY_FILTER_DOMAIN: (&(objectClass=user)(|(mail=%s)))
  LDAP_SEARCH_BASE: ou=Services-Account,dc=test,dc=internal
  LDAP_SERVER_HOST: ldaps://test-northeurope.smtp.test:636
  # <<< Postfix LDAP Integration
  # >>> Dovecot LDAP Integration
  DOVECOT_USER_FILTER: (&(objectClass=user)(cn=%u))
  DOVECOT_PASS_ATTRS: uniqueIdentifier=user,userPassword=password
  DOVECOT_USER_ATTRS: mailHomeDirectory=home,mailUidNumber=uid,mailGidNumber=gid,mailStorageDirectory=mail
  DOVECOT_AUTH_BIND: 'yes'
  # <<< Dovecot LDAP Integration
