apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- hpa.yaml
- namespace.yaml
- pdb.yaml
- service.yaml
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
configMapGenerator:
- name: smtp-user-patches
  files:
  - user-patches.sh
- name: smtp-postfix-maincf
  files:
  - postfix-main.cf
- name: mtail-progs
  files:
  - postfix.mtail
generatorOptions:
  disableNameSuffixHash: true
