apiVersion: v1
kind: Service
metadata:
  name: smtp
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: smtp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: smtp
  ports:
    - name: transfer
      port: 25
      targetPort: transfer
      protocol: TCP
    - name: esmtp-explicit
      port: 587
      targetPort: esmtp-explicit
      protocol: TCP
